import Head from "next/head";
const AboutUsPage = () => {
    return <>
    <Head>
            <title>About Us</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    <div>
        <h1>About Us</h1>
        <p> Lorem ipsum,Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Minima excepturi est ratione fuga maxime temporibus natus tempora
            laudantium et ipsum? dolor sit amet consectetur adipisicing elit. A
            met mollitia doloribus nulla, incidunt expedita quae doloremque alias eaque a!
            Provident cumque corporis reprehenderit vitae velit nulla accusamus et distinctio
            omnis, quisquam, ipsam dolorem eum!
        </p>
    </div>
    </>;
}

export default AboutUsPage;