import Head from "next/head";
const EventPage = ({ eventData }) => {
    return (
        <>
            <Head>
                <title>{eventData[0].title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <div>
                {eventData.map((event) => {
                    return (
                        <div key={event.id} className="pt-5 pl-5 flex flex-col items-center justify-center">
                            <img src={event.image} alt={event.title} className="w-[50%] h-[25%] rounded-2xl mb-4 solo-img" />
                            <h1 className="font-bold text-[36px] text-[#00ff00] text-grd mxs:text-[16px]">{event.title}</h1>
                            <p className="text-[#fde800] max-w-[550px] mxs:text-[12px]">{event.description}</p>
                            <div className="flex flex-row gap-2 pb-4 items-center justify-center">
                                <label htmlFor="" className="font-semibold text-[18px]">Email:</label>
                                <input type="email" name="" id="" className="rounded-md p-2 text-primary border-none" />
                                <button type="submit" className="rounded-md border-[1px] p-2 border-[#000000] bg-[#55ebe9] text-primary
                                 hover:text-[#00ff00] hover:bg-white font-semibold 
                                  font-ubuntu ">Submit</button>
                            </div>
                        </div>
                    )
                })}
            </div>
        </>);
}

export default EventPage;

export const getStaticPaths = async () => {
    const data = await import("/data/data.json");
    const allEvents = data.allEvents;

    const allPaths = allEvents.map((path) => {
        return {
            params: {
                cat: path.city.charAt(0).toLowerCase() + path.city.slice(1),
                // we will used id because we have used it in the file name
                id: path.id,
            }
        }
    })
    return {
        paths: allPaths,
        fallback: false
    };
}

export const getStaticProps = async (context) => {
    const { allEvents } = await import("/data/data.json");
    const id = context.params.id;
    const eventData = allEvents.filter((event) => event.id === id);

    return {
        props: { eventData },
    };
}