import Link from 'next/link';
import Head from 'next/head';

const EventsCatPage = ({ data, pageName }) => {
    return (
        <>
            <Head>
                <title>Events of {pageName}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1 className='text-[32px] font-bold text-gradient pt-5'>Events in {pageName}</h1>
                {data.map((cat) => (
                    <Link key={cat.id} href={`/events/${cat.city.charAt(0).toLowerCase() + cat.city.slice(1)}/${cat.id}`} passHref>
                        <h2 className='text-[24px] mt-5'>{cat.title}</h2>
                        <img src={cat.image} alt={cat.title} width={200} height={200} />
                    </Link>
                )
                )}
            </div >
        </>
    );
}

export default EventsCatPage;


export const getStaticPaths = async () => {
    const { events_categories } = await import("/data/data.json");
    const allPaths = events_categories.map((ct) => {
        return {
            params: {
                cat: ct.id.toString(),
            }
        }
    })

    return {
        paths: allPaths,
        fallback: false
    };
}

export const getStaticProps = async (context) => {
    const id = context.params.cat;
    const { allEvents } = await import("/data/data.json");
    const data = allEvents.filter(cat => cat.city === id.charAt(0).toUpperCase() + id.slice(1));
    return {
        props: {
            data,
            pageName: id.charAt(0).toUpperCase() + id.slice(1)
        }
    };
}
